/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package simrskhanza;

import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author perpustakaan
 */
public class DlgNomorAntrian extends javax.swing.JDialog {
    private validasi Valid = new validasi();
    private sekuel Sequel = new sekuel();
    private PreparedStatement ps, ps1, ps2, ps3, ps4;
    private ResultSet rs, rs1, rs2, rs3, rs4;
    private Connection koneksi = koneksiDB.condb();
    private final Properties prop = new Properties();
    private int i = 0, a = 0, b = 0, c = 0, d = 0;
    private SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
    private Date date = new Date();
    private String now = dateformat2.format(date), cekNomor = "", nmPrinter = "";
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");

    public DlgNomorAntrian(java.awt.Frame parent, boolean modal) {
        initComponents();
        
        TimerStart();        
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
            label_box.setText(koneksiDB.NOMORBOX());
            nmPrinter = koneksiDB.NAMAPRINTER1();
        } catch (Exception e) {
            System.out.println("SEP XML : "+e);
        }
                
        persenNomor();
//        cekKertas();
        angka.setDocument(new batasInput((byte) 4).getOnlyAngka(angka));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void formWindowOpened(java.awt.event.WindowEvent evt) {

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prosesTombol = new widget.ProgressBar();
        prosesNomor = new widget.ProgressBar();
        WindowPengaturan = new javax.swing.JDialog();
        internalFrame8 = new widget.InternalFrame();
        BtnAktif = new widget.Button();
        jLabel13 = new widget.Label();
        angka = new widget.TextBox();
        jLabel14 = new widget.Label();
        BtnNonAktif = new widget.Button();
        BtnSetUmum = new widget.Button();
        BtnSetBPJS = new widget.Button();
        BtnSetInap = new widget.Button();
        BtnSetKhusus = new widget.Button();
        BtnResUmum = new widget.Button();
        BtnResBPJS = new widget.Button();
        BtnResInap = new widget.Button();
        BtnResKhusus = new widget.Button();
        jLabel15 = new widget.Label();
        label_pesan = new widget.TextArea();
        satu = new widget.Button();
        dua = new widget.Button();
        tiga = new widget.Button();
        empat = new widget.Button();
        lima = new widget.Button();
        enam = new widget.Button();
        tujuh = new widget.Button();
        delapan = new widget.Button();
        sembilan = new widget.Button();
        nol = new widget.Button();
        backspace = new widget.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        BtnKeluar = new widget.Button();
        BtnCloseApp = new widget.Button();
        BtnResetAngka = new widget.Button();
        label_box = new widget.Label();
        WindowLogin = new javax.swing.JDialog();
        internalFrame10 = new widget.InternalFrame();
        jLabel8 = new javax.swing.JLabel();
        pinLogin = new widget.PasswordBox();
        ok = new widget.Button();
        logout = new widget.Button();
        internalFrame9 = new widget.InternalFrame();
        satu1 = new widget.Button();
        dua1 = new widget.Button();
        tiga1 = new widget.Button();
        empat1 = new widget.Button();
        lima1 = new widget.Button();
        enam1 = new widget.Button();
        tujuh1 = new widget.Button();
        delapan1 = new widget.Button();
        sembilan1 = new widget.Button();
        nol1 = new widget.Button();
        backspace1 = new widget.Button();
        buttonGroup1 = new javax.swing.ButtonGroup();
        kertas = new javax.swing.JLabel();
        BtnKertas = new widget.Button();
        internalFrame1 = new widget.InternalFrame();
        internalFrame3 = new widget.InternalFrame();
        label_judul1 = new javax.swing.JLabel();
        internalFrame2 = new widget.InternalFrame();
        label_judul2 = new javax.swing.JLabel();
        PanelUtama = new javax.swing.JPanel();
        scrollPane1 = new widget.ScrollPane();
        PanelWallNomor = new usu.widget.glass.PanelGlass();
        internalFrame5 = new widget.InternalFrame();
        tombol = new widget.InternalFrame();
        loket_umum = new widget.Button();
        loket_bpjs = new widget.Button();
        loket_inap = new widget.Button();
        loket_khusus = new widget.Button();
        internalFrame6 = new widget.InternalFrame();
        internalFrame7 = new widget.InternalFrame();
        label3 = new javax.swing.JLabel();
        labe4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        labe6 = new javax.swing.JLabel();
        antrian_terakhir = new widget.InternalFrame();
        no_loket_umum = new javax.swing.JLabel();
        no_loket_bpjs = new javax.swing.JLabel();
        no_loket_inap = new javax.swing.JLabel();
        no_loket_khusus = new javax.swing.JLabel();
        internalFrame4 = new widget.InternalFrame();
        seting = new widget.Button();

        prosesTombol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prosesTombol.setName("prosesTombol"); // NOI18N
        prosesTombol.setPreferredSize(new java.awt.Dimension(160, 40));
        prosesTombol.setStringPainted(true);

        prosesNomor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prosesNomor.setName("prosesNomor"); // NOI18N
        prosesNomor.setPreferredSize(new java.awt.Dimension(160, 40));
        prosesNomor.setStringPainted(true);

        WindowPengaturan.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowPengaturan.setName("WindowPengaturan"); // NOI18N
        WindowPengaturan.setUndecorated(true);
        WindowPengaturan.setResizable(false);

        internalFrame8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ PENGATURAN NOMOR ANTRIAN ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        internalFrame8.setName("internalFrame8"); // NOI18N
        internalFrame8.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame8.setLayout(null);

        BtnAktif.setForeground(new java.awt.Color(0, 0, 0));
        BtnAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/checked.png"))); // NOI18N
        BtnAktif.setText("TOMBOL AKTIF");
        BtnAktif.setToolTipText("");
        BtnAktif.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnAktif.setGlassColor(new java.awt.Color(0, 204, 255));
        BtnAktif.setIconTextGap(10);
        BtnAktif.setName("BtnAktif"); // NOI18N
        BtnAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAktifActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnAktif);
        BtnAktif.setBounds(30, 32, 200, 40);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("No. Box Anjungan : ");
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        internalFrame8.add(jLabel13);
        jLabel13.setBounds(0, 80, 300, 40);

        angka.setForeground(new java.awt.Color(0, 0, 0));
        angka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        angka.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        angka.setName("angka"); // NOI18N
        angka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                angkaKeyPressed(evt);
            }
        });
        internalFrame8.add(angka);
        angka.setBounds(302, 128, 120, 40);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Angka Pengaturan : ");
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        internalFrame8.add(jLabel14);
        jLabel14.setBounds(0, 128, 300, 40);

        BtnNonAktif.setForeground(new java.awt.Color(0, 0, 0));
        BtnNonAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/lock.png"))); // NOI18N
        BtnNonAktif.setText("TOMBOL NON AKTIF");
        BtnNonAktif.setToolTipText("");
        BtnNonAktif.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnNonAktif.setGlassColor(new java.awt.Color(0, 204, 255));
        BtnNonAktif.setName("BtnNonAktif"); // NOI18N
        BtnNonAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNonAktifActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnNonAktif);
        BtnNonAktif.setBounds(240, 32, 240, 40);

        BtnSetUmum.setForeground(new java.awt.Color(0, 0, 0));
        BtnSetUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnSetUmum.setText("SET ANTRIAN RAWAT JALAN UMUM (NON BPJS)");
        BtnSetUmum.setToolTipText("");
        BtnSetUmum.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BtnSetUmum.setGlassColor(new java.awt.Color(0, 0, 0));
        BtnSetUmum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSetUmum.setIconTextGap(10);
        BtnSetUmum.setName("BtnSetUmum"); // NOI18N
        BtnSetUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSetUmumActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnSetUmum);
        BtnSetUmum.setBounds(30, 176, 452, 50);

        BtnSetBPJS.setForeground(new java.awt.Color(0, 0, 0));
        BtnSetBPJS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnSetBPJS.setText("SET ANTRIAN RAWAT JALAN UMUM BPJS");
        BtnSetBPJS.setToolTipText("");
        BtnSetBPJS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnSetBPJS.setGlassColor(new java.awt.Color(0, 153, 0));
        BtnSetBPJS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSetBPJS.setIconTextGap(10);
        BtnSetBPJS.setName("BtnSetBPJS"); // NOI18N
        BtnSetBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSetBPJSActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnSetBPJS);
        BtnSetBPJS.setBounds(30, 235, 452, 50);

        BtnSetInap.setForeground(new java.awt.Color(0, 0, 0));
        BtnSetInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnSetInap.setText("SET ANTRIAN RAWAT INAP");
        BtnSetInap.setToolTipText("");
        BtnSetInap.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        BtnSetInap.setGlassColor(new java.awt.Color(255, 255, 0));
        BtnSetInap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSetInap.setIconTextGap(10);
        BtnSetInap.setName("BtnSetInap"); // NOI18N
        BtnSetInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSetInapActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnSetInap);
        BtnSetInap.setBounds(30, 294, 452, 50);

        BtnSetKhusus.setForeground(new java.awt.Color(0, 0, 0));
        BtnSetKhusus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816018_tests.png"))); // NOI18N
        BtnSetKhusus.setText("SET ANTRIAN RAWAT JALAN (KHUSUS)");
        BtnSetKhusus.setToolTipText("");
        BtnSetKhusus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnSetKhusus.setGlassColor(new java.awt.Color(153, 0, 153));
        BtnSetKhusus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSetKhusus.setIconTextGap(10);
        BtnSetKhusus.setName("BtnSetKhusus"); // NOI18N
        BtnSetKhusus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSetKhususActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnSetKhusus);
        BtnSetKhusus.setBounds(30, 353, 452, 50);

        BtnResUmum.setForeground(new java.awt.Color(0, 0, 0));
        BtnResUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816189_arrow_down.png"))); // NOI18N
        BtnResUmum.setText("RESET");
        BtnResUmum.setToolTipText("");
        BtnResUmum.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnResUmum.setGlassColor(new java.awt.Color(0, 0, 0));
        BtnResUmum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResUmum.setIconTextGap(10);
        BtnResUmum.setName("BtnResUmum"); // NOI18N
        BtnResUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResUmumActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnResUmum);
        BtnResUmum.setBounds(492, 176, 150, 50);

        BtnResBPJS.setForeground(new java.awt.Color(0, 0, 0));
        BtnResBPJS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816189_arrow_down.png"))); // NOI18N
        BtnResBPJS.setText("RESET");
        BtnResBPJS.setToolTipText("");
        BtnResBPJS.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnResBPJS.setGlassColor(new java.awt.Color(0, 153, 0));
        BtnResBPJS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResBPJS.setIconTextGap(10);
        BtnResBPJS.setName("BtnResBPJS"); // NOI18N
        BtnResBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResBPJSActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnResBPJS);
        BtnResBPJS.setBounds(492, 235, 150, 50);

        BtnResInap.setForeground(new java.awt.Color(0, 0, 0));
        BtnResInap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816189_arrow_down.png"))); // NOI18N
        BtnResInap.setText("RESET");
        BtnResInap.setToolTipText("");
        BtnResInap.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnResInap.setGlassColor(new java.awt.Color(255, 255, 0));
        BtnResInap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResInap.setIconTextGap(10);
        BtnResInap.setName("BtnResInap"); // NOI18N
        BtnResInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResInapActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnResInap);
        BtnResInap.setBounds(492, 294, 150, 50);

        BtnResKhusus.setForeground(new java.awt.Color(0, 0, 0));
        BtnResKhusus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360816189_arrow_down.png"))); // NOI18N
        BtnResKhusus.setText("RESET");
        BtnResKhusus.setToolTipText("");
        BtnResKhusus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnResKhusus.setGlassColor(new java.awt.Color(153, 0, 153));
        BtnResKhusus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnResKhusus.setIconTextGap(10);
        BtnResKhusus.setName("BtnResKhusus"); // NOI18N
        BtnResKhusus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResKhususActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnResKhusus);
        BtnResKhusus.setBounds(492, 353, 150, 50);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Informasi : ");
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        internalFrame8.add(jLabel15);
        jLabel15.setBounds(0, 412, 110, 23);

        label_pesan.setEditable(false);
        label_pesan.setColumns(20);
        label_pesan.setForeground(new java.awt.Color(0, 0, 0));
        label_pesan.setRows(5);
        label_pesan.setText("Apa yang anda pikirkan...!!!");
        label_pesan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_pesan.setHighlighter(null);
        label_pesan.setName("label_pesan"); // NOI18N
        internalFrame8.add(label_pesan);
        label_pesan.setBounds(25, 427, 740, 140);

        satu.setForeground(new java.awt.Color(0, 0, 0));
        satu.setText("1");
        satu.setToolTipText("");
        satu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        satu.setGlassColor(new java.awt.Color(102, 204, 255));
        satu.setName("satu"); // NOI18N
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        internalFrame8.add(satu);
        satu.setBounds(670, 40, 80, 80);

        dua.setForeground(new java.awt.Color(0, 0, 0));
        dua.setText("2");
        dua.setToolTipText("");
        dua.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        dua.setGlassColor(new java.awt.Color(102, 204, 255));
        dua.setName("dua"); // NOI18N
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        internalFrame8.add(dua);
        dua.setBounds(760, 40, 80, 80);

        tiga.setForeground(new java.awt.Color(0, 0, 0));
        tiga.setText("3");
        tiga.setToolTipText("");
        tiga.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        tiga.setGlassColor(new java.awt.Color(102, 204, 255));
        tiga.setName("tiga"); // NOI18N
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        internalFrame8.add(tiga);
        tiga.setBounds(850, 40, 80, 80);

        empat.setForeground(new java.awt.Color(0, 0, 0));
        empat.setText("4");
        empat.setToolTipText("");
        empat.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        empat.setGlassColor(new java.awt.Color(102, 204, 255));
        empat.setName("empat"); // NOI18N
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        internalFrame8.add(empat);
        empat.setBounds(670, 130, 80, 80);

        lima.setForeground(new java.awt.Color(0, 0, 0));
        lima.setText("5");
        lima.setToolTipText("");
        lima.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lima.setGlassColor(new java.awt.Color(102, 204, 255));
        lima.setName("lima"); // NOI18N
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        internalFrame8.add(lima);
        lima.setBounds(760, 130, 80, 80);

        enam.setForeground(new java.awt.Color(0, 0, 0));
        enam.setText("6");
        enam.setToolTipText("");
        enam.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        enam.setGlassColor(new java.awt.Color(102, 204, 255));
        enam.setName("enam"); // NOI18N
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        internalFrame8.add(enam);
        enam.setBounds(850, 130, 80, 80);

        tujuh.setForeground(new java.awt.Color(0, 0, 0));
        tujuh.setText("7");
        tujuh.setToolTipText("");
        tujuh.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        tujuh.setGlassColor(new java.awt.Color(102, 204, 255));
        tujuh.setName("tujuh"); // NOI18N
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        internalFrame8.add(tujuh);
        tujuh.setBounds(670, 220, 80, 80);

        delapan.setForeground(new java.awt.Color(0, 0, 0));
        delapan.setText("8");
        delapan.setToolTipText("");
        delapan.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        delapan.setGlassColor(new java.awt.Color(102, 204, 255));
        delapan.setName("delapan"); // NOI18N
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        internalFrame8.add(delapan);
        delapan.setBounds(760, 220, 80, 80);

        sembilan.setForeground(new java.awt.Color(0, 0, 0));
        sembilan.setText("9");
        sembilan.setToolTipText("");
        sembilan.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        sembilan.setGlassColor(new java.awt.Color(102, 204, 255));
        sembilan.setName("sembilan"); // NOI18N
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        internalFrame8.add(sembilan);
        sembilan.setBounds(850, 220, 80, 80);

        nol.setForeground(new java.awt.Color(0, 0, 0));
        nol.setText("0");
        nol.setToolTipText("");
        nol.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        nol.setGlassColor(new java.awt.Color(102, 204, 255));
        nol.setName("nol"); // NOI18N
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        internalFrame8.add(nol);
        nol.setBounds(670, 310, 80, 80);

        backspace.setForeground(new java.awt.Color(0, 0, 0));
        backspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png"))); // NOI18N
        backspace.setText("backspace");
        backspace.setToolTipText("");
        backspace.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        backspace.setGlassColor(new java.awt.Color(102, 204, 255));
        backspace.setName("backspace"); // NOI18N
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });
        internalFrame8.add(backspace);
        backspace.setBounds(760, 310, 170, 80);

        jSeparator1.setName("jSeparator1"); // NOI18N
        internalFrame8.add(jSeparator1);
        jSeparator1.setBounds(650, 26, 300, 10);

        jSeparator2.setName("jSeparator2"); // NOI18N
        internalFrame8.add(jSeparator2);
        jSeparator2.setBounds(650, 400, 300, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setName("jSeparator3"); // NOI18N
        internalFrame8.add(jSeparator3);
        jSeparator3.setBounds(650, 26, 10, 375);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setName("jSeparator4"); // NOI18N
        internalFrame8.add(jSeparator4);
        jSeparator4.setBounds(950, 26, 10, 375);

        BtnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/preferences-desktop-cryptography.png"))); // NOI18N
        BtnKeluar.setText("KELUAR");
        BtnKeluar.setToolTipText("");
        BtnKeluar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnKeluar.setGlassColor(new java.awt.Color(102, 204, 255));
        BtnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKeluar.setIconTextGap(10);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        internalFrame8.add(BtnKeluar);
        BtnKeluar.setBounds(780, 412, 170, 60);

        BtnCloseApp.setForeground(new java.awt.Color(0, 0, 0));
        BtnCloseApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Delete.png"))); // NOI18N
        BtnCloseApp.setText("Close App.");
        BtnCloseApp.setToolTipText("");
        BtnCloseApp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnCloseApp.setGlassColor(new java.awt.Color(0, 204, 255));
        BtnCloseApp.setName("BtnCloseApp"); // NOI18N
        BtnCloseApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseAppActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnCloseApp);
        BtnCloseApp.setBounds(492, 128, 150, 40);

        BtnResetAngka.setForeground(new java.awt.Color(0, 0, 0));
        BtnResetAngka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnResetAngka.setToolTipText("");
        BtnResetAngka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnResetAngka.setGlassColor(new java.awt.Color(0, 204, 255));
        BtnResetAngka.setName("BtnResetAngka"); // NOI18N
        BtnResetAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetAngkaActionPerformed(evt);
            }
        });
        internalFrame8.add(BtnResetAngka);
        BtnResetAngka.setBounds(430, 128, 53, 40);

        label_box.setForeground(new java.awt.Color(0, 0, 0));
        label_box.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_box.setText("label_box");
        label_box.setFont(new java.awt.Font("Tahoma", 3, 27)); // NOI18N
        label_box.setName("label_box"); // NOI18N
        internalFrame8.add(label_box);
        label_box.setBounds(302, 80, 230, 40);

        WindowPengaturan.getContentPane().add(internalFrame8, java.awt.BorderLayout.CENTER);

        WindowLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowLogin.setName("WindowLogin"); // NOI18N
        WindowLogin.setUndecorated(true);
        WindowLogin.setResizable(false);

        internalFrame10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ LOGIN USER ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        internalFrame10.setName("internalFrame10"); // NOI18N
        internalFrame10.setPreferredSize(new java.awt.Dimension(0, 90));
        internalFrame10.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 9, 5));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("PIN :");
        jLabel8.setToolTipText("");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 44));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        internalFrame10.add(jLabel8);

        pinLogin.setForeground(new java.awt.Color(0, 0, 0));
        pinLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinLogin.setToolTipText("");
        pinLogin.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        pinLogin.setName("pinLogin"); // NOI18N
        pinLogin.setPreferredSize(new java.awt.Dimension(110, 43));
        pinLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pinLoginKeyPressed(evt);
            }
        });
        internalFrame10.add(pinLogin);

        ok.setForeground(new java.awt.Color(0, 0, 0));
        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/system-software-update.png"))); // NOI18N
        ok.setToolTipText("");
        ok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ok.setGlassColor(new java.awt.Color(102, 204, 255));
        ok.setName("ok"); // NOI18N
        ok.setPreferredSize(new java.awt.Dimension(50, 50));
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        internalFrame10.add(ok);

        logout.setForeground(new java.awt.Color(0, 0, 0));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/logout.png"))); // NOI18N
        logout.setToolTipText("");
        logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logout.setGlassColor(new java.awt.Color(102, 204, 255));
        logout.setName("logout"); // NOI18N
        logout.setPreferredSize(new java.awt.Dimension(50, 50));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        internalFrame10.add(logout);

        WindowLogin.getContentPane().add(internalFrame10, java.awt.BorderLayout.PAGE_START);

        internalFrame9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ MASUKKAN PIN ANDA ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        internalFrame9.setName("internalFrame9"); // NOI18N
        internalFrame9.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame9.setLayout(null);

        satu1.setForeground(new java.awt.Color(0, 0, 0));
        satu1.setText("1");
        satu1.setToolTipText("");
        satu1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        satu1.setGlassColor(new java.awt.Color(102, 204, 255));
        satu1.setName("satu1"); // NOI18N
        satu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satu1ActionPerformed(evt);
            }
        });
        internalFrame9.add(satu1);
        satu1.setBounds(20, 30, 80, 80);

        dua1.setForeground(new java.awt.Color(0, 0, 0));
        dua1.setText("2");
        dua1.setToolTipText("");
        dua1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        dua1.setGlassColor(new java.awt.Color(102, 204, 255));
        dua1.setName("dua1"); // NOI18N
        dua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dua1ActionPerformed(evt);
            }
        });
        internalFrame9.add(dua1);
        dua1.setBounds(110, 30, 80, 80);

        tiga1.setForeground(new java.awt.Color(0, 0, 0));
        tiga1.setText("3");
        tiga1.setToolTipText("");
        tiga1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        tiga1.setGlassColor(new java.awt.Color(102, 204, 255));
        tiga1.setName("tiga1"); // NOI18N
        tiga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiga1ActionPerformed(evt);
            }
        });
        internalFrame9.add(tiga1);
        tiga1.setBounds(200, 30, 80, 80);

        empat1.setForeground(new java.awt.Color(0, 0, 0));
        empat1.setText("4");
        empat1.setToolTipText("");
        empat1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        empat1.setGlassColor(new java.awt.Color(102, 204, 255));
        empat1.setName("empat1"); // NOI18N
        empat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empat1ActionPerformed(evt);
            }
        });
        internalFrame9.add(empat1);
        empat1.setBounds(20, 120, 80, 80);

        lima1.setForeground(new java.awt.Color(0, 0, 0));
        lima1.setText("5");
        lima1.setToolTipText("");
        lima1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lima1.setGlassColor(new java.awt.Color(102, 204, 255));
        lima1.setName("lima1"); // NOI18N
        lima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lima1ActionPerformed(evt);
            }
        });
        internalFrame9.add(lima1);
        lima1.setBounds(110, 120, 80, 80);

        enam1.setForeground(new java.awt.Color(0, 0, 0));
        enam1.setText("6");
        enam1.setToolTipText("");
        enam1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        enam1.setGlassColor(new java.awt.Color(102, 204, 255));
        enam1.setName("enam1"); // NOI18N
        enam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enam1ActionPerformed(evt);
            }
        });
        internalFrame9.add(enam1);
        enam1.setBounds(200, 120, 80, 80);

        tujuh1.setForeground(new java.awt.Color(0, 0, 0));
        tujuh1.setText("7");
        tujuh1.setToolTipText("");
        tujuh1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        tujuh1.setGlassColor(new java.awt.Color(102, 204, 255));
        tujuh1.setName("tujuh1"); // NOI18N
        tujuh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuh1ActionPerformed(evt);
            }
        });
        internalFrame9.add(tujuh1);
        tujuh1.setBounds(20, 210, 80, 80);

        delapan1.setForeground(new java.awt.Color(0, 0, 0));
        delapan1.setText("8");
        delapan1.setToolTipText("");
        delapan1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        delapan1.setGlassColor(new java.awt.Color(102, 204, 255));
        delapan1.setName("delapan1"); // NOI18N
        delapan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapan1ActionPerformed(evt);
            }
        });
        internalFrame9.add(delapan1);
        delapan1.setBounds(110, 210, 80, 80);

        sembilan1.setForeground(new java.awt.Color(0, 0, 0));
        sembilan1.setText("9");
        sembilan1.setToolTipText("");
        sembilan1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        sembilan1.setGlassColor(new java.awt.Color(102, 204, 255));
        sembilan1.setName("sembilan1"); // NOI18N
        sembilan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilan1ActionPerformed(evt);
            }
        });
        internalFrame9.add(sembilan1);
        sembilan1.setBounds(200, 210, 80, 80);

        nol1.setForeground(new java.awt.Color(0, 0, 0));
        nol1.setText("0");
        nol1.setToolTipText("");
        nol1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        nol1.setGlassColor(new java.awt.Color(102, 204, 255));
        nol1.setName("nol1"); // NOI18N
        nol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nol1ActionPerformed(evt);
            }
        });
        internalFrame9.add(nol1);
        nol1.setBounds(20, 300, 80, 80);

        backspace1.setForeground(new java.awt.Color(0, 0, 0));
        backspace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485642_edit-notes.png"))); // NOI18N
        backspace1.setText("backspace");
        backspace1.setToolTipText("");
        backspace1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        backspace1.setGlassColor(new java.awt.Color(102, 204, 255));
        backspace1.setName("backspace1"); // NOI18N
        backspace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspace1ActionPerformed(evt);
            }
        });
        internalFrame9.add(backspace1);
        backspace1.setBounds(110, 300, 170, 80);

        WindowLogin.getContentPane().add(internalFrame9, java.awt.BorderLayout.CENTER);

        kertas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kertas.setForeground(new java.awt.Color(255, 255, 255));
        kertas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kertas.setText("kertas");
        kertas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kertas.setName("kertas"); // NOI18N
        kertas.setPreferredSize(new java.awt.Dimension(550, 23));

        BtnKertas.setForeground(new java.awt.Color(0, 0, 0));
        BtnKertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485894_add-notes.png"))); // NOI18N
        BtnKertas.setText("RESET COUNTER KERTAS");
        BtnKertas.setToolTipText("");
        BtnKertas.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        BtnKertas.setGlassColor(new java.awt.Color(255, 0, 0));
        BtnKertas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKertas.setIconTextGap(10);
        BtnKertas.setName("BtnKertas"); // NOI18N
        BtnKertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKertasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setBackground(new java.awt.Color(83, 204, 251));
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(null);
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setOpaque(false);
        internalFrame1.setPreferredSize(new java.awt.Dimension(0, 80));
        internalFrame1.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame3.setBorder(null);
        internalFrame3.setName("internalFrame3"); // NOI18N
        internalFrame3.setPreferredSize(new java.awt.Dimension(0, 40));
        internalFrame3.setWarnaAtas(new java.awt.Color(83, 204, 251));
        internalFrame3.setWarnaBawah(new java.awt.Color(83, 204, 251));
        internalFrame3.setLayout(new java.awt.BorderLayout());

        label_judul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_judul1.setText("SILAHKAN TEKAN TOMBOL YANG ANDA PILIH");
        label_judul1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_judul1.setName("label_judul1"); // NOI18N
        label_judul1.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame3.add(label_judul1, java.awt.BorderLayout.CENTER);

        internalFrame1.add(internalFrame3, java.awt.BorderLayout.PAGE_START);

        internalFrame2.setBorder(null);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(0, 40));
        internalFrame2.setWarnaAtas(new java.awt.Color(83, 204, 251));
        internalFrame2.setWarnaBawah(new java.awt.Color(83, 204, 251));
        internalFrame2.setLayout(new java.awt.BorderLayout());

        label_judul2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_judul2.setText("UNTUK MENGAMBIL NOMOR ANTRIAN");
        label_judul2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_judul2.setName("label_judul2"); // NOI18N
        label_judul2.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame2.add(label_judul2, java.awt.BorderLayout.CENTER);

        internalFrame1.add(internalFrame2, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.PAGE_START);

        PanelUtama.setName("PanelUtama"); // NOI18N
        PanelUtama.setOpaque(false);
        PanelUtama.setLayout(new java.awt.BorderLayout());

        scrollPane1.setBorder(null);
        scrollPane1.setName("scrollPane1"); // NOI18N

        PanelWallNomor.setBackground(new java.awt.Color(29, 29, 29));
        PanelWallNomor.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpaper_antrian.jpg"))); // NOI18N
        PanelWallNomor.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWallNomor.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        PanelWallNomor.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelWallNomor.setRound(false);
        PanelWallNomor.setWarna(new java.awt.Color(204, 204, 204));
        PanelWallNomor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PanelWallNomorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        PanelWallNomor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelWallNomorMouseClicked(evt);
            }
        });
        PanelWallNomor.setLayout(new java.awt.BorderLayout());

        internalFrame5.setBorder(null);
        internalFrame5.setName("internalFrame5"); // NOI18N
        internalFrame5.setOpaque(false);
        internalFrame5.setPreferredSize(new java.awt.Dimension(0, 350));
        internalFrame5.setLayout(new java.awt.BorderLayout());

        tombol.setBorder(null);
        tombol.setName("tombol"); // NOI18N
        tombol.setOpaque(false);
        tombol.setPreferredSize(new java.awt.Dimension(330, 328));
        tombol.setWarnaAtas(new java.awt.Color(255, 255, 255));
        tombol.setWarnaBawah(new java.awt.Color(255, 204, 0));
        tombol.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 15));

        loket_umum.setBorder(null);
        loket_umum.setForeground(new java.awt.Color(0, 0, 0));
        loket_umum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/loket_umum.png"))); // NOI18N
        loket_umum.setToolTipText("");
        loket_umum.setBorderPainted(true);
        loket_umum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loket_umum.setGlassColor(new java.awt.Color(0, 0, 0));
        loket_umum.setName("loket_umum"); // NOI18N
        loket_umum.setPreferredSize(new java.awt.Dimension(300, 300));
        loket_umum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loket_umumActionPerformed(evt);
            }
        });
        tombol.add(loket_umum);

        loket_bpjs.setBackground(new java.awt.Color(0, 153, 51));
        loket_bpjs.setBorder(null);
        loket_bpjs.setForeground(new java.awt.Color(0, 0, 0));
        loket_bpjs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/loket_bpjs.png"))); // NOI18N
        loket_bpjs.setToolTipText("");
        loket_bpjs.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loket_bpjs.setGlassColor(new java.awt.Color(0, 102, 0));
        loket_bpjs.setName("loket_bpjs"); // NOI18N
        loket_bpjs.setPreferredSize(new java.awt.Dimension(300, 300));
        loket_bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loket_bpjsActionPerformed(evt);
            }
        });
        tombol.add(loket_bpjs);

        loket_inap.setBackground(new java.awt.Color(255, 255, 0));
        loket_inap.setBorder(null);
        loket_inap.setForeground(new java.awt.Color(0, 0, 0));
        loket_inap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/loket_inap.png"))); // NOI18N
        loket_inap.setToolTipText("");
        loket_inap.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loket_inap.setGlassColor(new java.awt.Color(255, 255, 0));
        loket_inap.setName("loket_inap"); // NOI18N
        loket_inap.setPreferredSize(new java.awt.Dimension(300, 300));
        loket_inap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loket_inapActionPerformed(evt);
            }
        });
        tombol.add(loket_inap);

        loket_khusus.setBackground(new java.awt.Color(204, 0, 204));
        loket_khusus.setBorder(null);
        loket_khusus.setForeground(new java.awt.Color(0, 0, 0));
        loket_khusus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/loket_khusus.png"))); // NOI18N
        loket_khusus.setToolTipText("");
        loket_khusus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loket_khusus.setGlassColor(new java.awt.Color(255, 0, 204));
        loket_khusus.setName("loket_khusus"); // NOI18N
        loket_khusus.setPreferredSize(new java.awt.Dimension(300, 300));
        loket_khusus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loket_khususActionPerformed(evt);
            }
        });
        tombol.add(loket_khusus);

        internalFrame5.add(tombol, java.awt.BorderLayout.PAGE_END);

        PanelWallNomor.add(internalFrame5, java.awt.BorderLayout.PAGE_START);

        internalFrame6.setBorder(null);
        internalFrame6.setName("internalFrame6"); // NOI18N
        internalFrame6.setOpaque(false);
        internalFrame6.setPreferredSize(new java.awt.Dimension(0, 430));
        internalFrame6.setLayout(new java.awt.BorderLayout());

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setOpaque(false);
        internalFrame7.setPreferredSize(new java.awt.Dimension(330, 35));
        internalFrame7.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame7.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 0));

        label3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Nomor Antrian");
        label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label3.setName("label3"); // NOI18N
        label3.setPreferredSize(new java.awt.Dimension(300, 35));
        internalFrame7.add(label3);

        labe4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labe4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labe4.setText("Nomor Antrian");
        labe4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labe4.setName("labe4"); // NOI18N
        labe4.setPreferredSize(new java.awt.Dimension(300, 35));
        internalFrame7.add(labe4);

        label5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("Nomor Antrian");
        label5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label5.setName("label5"); // NOI18N
        label5.setPreferredSize(new java.awt.Dimension(300, 35));
        internalFrame7.add(label5);

        labe6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labe6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labe6.setText("Nomor Antrian");
        labe6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labe6.setName("labe6"); // NOI18N
        labe6.setPreferredSize(new java.awt.Dimension(300, 35));
        internalFrame7.add(labe6);

        internalFrame6.add(internalFrame7, java.awt.BorderLayout.PAGE_START);

        antrian_terakhir.setBorder(null);
        antrian_terakhir.setName("antrian_terakhir"); // NOI18N
        antrian_terakhir.setOpaque(false);
        antrian_terakhir.setPreferredSize(new java.awt.Dimension(330, 50));
        antrian_terakhir.setWarnaAtas(new java.awt.Color(255, 255, 255));
        antrian_terakhir.setWarnaBawah(new java.awt.Color(255, 204, 0));
        antrian_terakhir.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 0));

        no_loket_umum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no_loket_umum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_loket_umum.setText("Terakhir : ");
        no_loket_umum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_loket_umum.setName("no_loket_umum"); // NOI18N
        no_loket_umum.setPreferredSize(new java.awt.Dimension(300, 35));
        antrian_terakhir.add(no_loket_umum);

        no_loket_bpjs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no_loket_bpjs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_loket_bpjs.setText("Terakhir : ");
        no_loket_bpjs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_loket_bpjs.setName("no_loket_bpjs"); // NOI18N
        no_loket_bpjs.setPreferredSize(new java.awt.Dimension(300, 35));
        antrian_terakhir.add(no_loket_bpjs);

        no_loket_inap.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no_loket_inap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_loket_inap.setText("Terakhir : ");
        no_loket_inap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_loket_inap.setName("no_loket_inap"); // NOI18N
        no_loket_inap.setPreferredSize(new java.awt.Dimension(300, 35));
        antrian_terakhir.add(no_loket_inap);

        no_loket_khusus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no_loket_khusus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_loket_khusus.setText("Terakhir : ");
        no_loket_khusus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_loket_khusus.setName("no_loket_khusus"); // NOI18N
        no_loket_khusus.setPreferredSize(new java.awt.Dimension(300, 35));
        antrian_terakhir.add(no_loket_khusus);

        internalFrame6.add(antrian_terakhir, java.awt.BorderLayout.CENTER);

        PanelWallNomor.add(internalFrame6, java.awt.BorderLayout.CENTER);

        internalFrame4.setBorder(null);
        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setOpaque(false);
        internalFrame4.setWarnaAtas(new java.awt.Color(255, 204, 0));
        internalFrame4.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        seting.setBorder(null);
        seting.setForeground(new java.awt.Color(0, 0, 0));
        seting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/our_process_2.png"))); // NOI18N
        seting.setToolTipText("");
        seting.setBorderPainted(true);
        seting.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        seting.setGlassColor(new java.awt.Color(0, 0, 0));
        seting.setName("seting"); // NOI18N
        seting.setPreferredSize(new java.awt.Dimension(60, 60));
        seting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setingActionPerformed(evt);
            }
        });
        internalFrame4.add(seting);

        PanelWallNomor.add(internalFrame4, java.awt.BorderLayout.PAGE_END);

        scrollPane1.setViewportView(PanelWallNomor);

        PanelUtama.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loket_inapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loket_inapActionPerformed
        cekNomor = "";
        cekNomor = "ya";
        loket_umum.setEnabled(false);
        loket_bpjs.setEnabled(false);
        loket_inap.setEnabled(false);
        loket_khusus.setEnabled(false);
        persenTombol();
//        kertasTerpotong();
        persenNomor();
        NoAntrianINAP();
    }//GEN-LAST:event_loket_inapActionPerformed

    private void loket_khususActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loket_khususActionPerformed
        cekNomor = "";
        cekNomor = "ya";
        loket_umum.setEnabled(false);
        loket_bpjs.setEnabled(false);
        loket_inap.setEnabled(false);
        loket_khusus.setEnabled(false);
        persenTombol();
//        kertasTerpotong();
        persenNomor();
        NoAntrianKHUSUS();
    }//GEN-LAST:event_loket_khususActionPerformed

    private void setingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setingActionPerformed
        cekNomor = "";
        cekNomor = "ya";
        loket_umum.setEnabled(false);
        loket_bpjs.setEnabled(false);
        loket_inap.setEnabled(false);
        loket_khusus.setEnabled(false);

        WindowLogin.setSize(341, 485);
        WindowLogin.setLocationRelativeTo(PanelUtama);
        WindowLogin.setVisible(true);
        pinLogin.setText("");
        pinLogin.requestFocus();
    }//GEN-LAST:event_setingActionPerformed

    private void BtnKertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKertasActionPerformed
        Sequel.mengedit("antrian_set_kertas", "kd_kertas='" + label_box.getText() + "'", "counter_kertas_antrian=0");
        label_pesan.setText("Penghitungan kertas terpotong berhasil diatur ulang...");
        BtnKeluarActionPerformed(null);
        cekTIDAK();
    }//GEN-LAST:event_BtnKertasActionPerformed

    private void BtnSetUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSetUmumActionPerformed
        if (angka.getText().equals("")) {
            label_pesan.setText("Angka pengaturan masih belum terisi dengan benar..!!");
            angka.requestFocus();
        } else {
            a = 0;
            a = Integer.parseInt(angka.getText());
            
            for (i = 0; i < a; i++) {
                Sequel.menyimpan("antrian_nomor_umum", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_umum where date(waktu_cetak)=date(now())") + "',"
                        + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan Umum (Non BPJS)");
            }
            
            label_pesan.setText("Pengurutan nomor antrian pasien Rawat Jalan Umum (Non BPJS) telah terseting sebanyak " + angka.getText() + " nomor antrian...!!!");
            angka.setText("");
        }
    }//GEN-LAST:event_BtnSetUmumActionPerformed

    private void BtnSetBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSetBPJSActionPerformed
        if (angka.getText().equals("")) {
            label_pesan.setText("Angka pengaturan masih belum terisi dengan benar..!!");
            angka.requestFocus();
        } else {
            a = 0;
            a = Integer.parseInt(angka.getText());
            
            for (i = 0; i < a; i++) {
                Sequel.menyimpan("antrian_nomor_bpjs", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_bpjs where date(waktu_cetak)=date(now())") + "',"
                        + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan BPJS");
            }
            
            label_pesan.setText("Pengurutan nomor antrian pasien Rawat Jalan BPJS telah terseting sebanyak " + angka.getText() + " nomor antrian...!!!");
            angka.setText("");
        }
    }//GEN-LAST:event_BtnSetBPJSActionPerformed

    private void BtnSetInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSetInapActionPerformed
        if (angka.getText().equals("")) {
            label_pesan.setText("Angka pengaturan masih belum terisi dengan benar..!!");
            angka.requestFocus();
        } else {
            a = 0;
            a = Integer.parseInt(angka.getText());

            for (i = 0; i < a; i++) {
                Sequel.menyimpan("antrian_nomor_inap", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_inap where date(waktu_cetak)=date(now())") + "',"
                        + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Inap");
            }

            label_pesan.setText("Pengurutan nomor antrian pasien Rawat Inap telah terseting sebanyak " + angka.getText() + " nomor antrian...!!!");
            angka.setText("");
        }
    }//GEN-LAST:event_BtnSetInapActionPerformed

    private void BtnSetKhususActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSetKhususActionPerformed
        if (angka.getText().equals("")) {
            label_pesan.setText("Angka pengaturan masih belum terisi dengan benar..!!");
            angka.requestFocus();
        } else {
            a = 0;
            a = Integer.parseInt(angka.getText());

            for (i = 0; i < a; i++) {
                Sequel.menyimpan("antrian_nomor_lansia", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_lansia where date(waktu_cetak)=date(now())") + "',"
                        + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan (KHUSUS / PRIORITAS)");
            }

            label_pesan.setText("Pengurutan nomor antrian pasien Rawat Jalan (KHUSUS / PRIORITAS) telah terseting sebanyak " + angka.getText() + " nomor antrian...!!!");
            angka.setText("");
        }
    }//GEN-LAST:event_BtnSetKhususActionPerformed

    private void BtnResUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResUmumActionPerformed
        Sequel.queryu("delete from antrian_nomor_umum");
        label_pesan.setText("Nomor antrian pasien RAWAT JALAN UMUM (NON BPJS) telah dimulai dari angka NOL (0), silakan tekan tombol aktif untuk mengaktifkan tombol loket.");
        no_loket_umum.setText("Terakhir : 0");
    }//GEN-LAST:event_BtnResUmumActionPerformed

    private void BtnResBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResBPJSActionPerformed
        Sequel.queryu("delete from antrian_nomor_bpjs");
        label_pesan.setText("Nomor antrian pasien RAWAT JALAN BPJS telah dimulai dari angka NOL (0), silakan tekan tombol aktif untuk mengaktifkan tombol loket.");
        no_loket_bpjs.setText("Terakhir : 0");
    }//GEN-LAST:event_BtnResBPJSActionPerformed

    private void BtnResInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResInapActionPerformed
        Sequel.queryu("delete from antrian_nomor_inap");
        label_pesan.setText("Nomor antrian pasien RAWAT INAP telah dimulai dari angka NOL (0), silakan tekan tombol aktif untuk mengaktifkan tombol loket.");
        no_loket_inap.setText("Terakhir : 0");
    }//GEN-LAST:event_BtnResInapActionPerformed

    private void BtnResKhususActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResKhususActionPerformed
        Sequel.queryu("delete from antrian_nomor_lansia");
        label_pesan.setText("Nomor antrian pasien RAWAT JALAN (KHUSUS / PRIORITAS) telah dimulai dari angka NOL (0), silakan tekan tombol aktif untuk mengaktifkan tombol loket.");
        no_loket_khusus.setText("Terakhir : 0");
    }//GEN-LAST:event_BtnResKhususActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        WindowLogin.dispose();
        pinLogin.setText("");
        WindowPengaturan.dispose();        
        angka.setText("");
//        persenKertas();
//        cekKertas();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void PanelWallNomorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelWallNomorMouseClicked
        BtnKeluarActionPerformed(null);
    }//GEN-LAST:event_PanelWallNomorMouseClicked

    private void PanelWallNomorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PanelWallNomorAncestorAdded
        BtnKeluarActionPerformed(null);
    }//GEN-LAST:event_PanelWallNomorAncestorAdded

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        angka.setText(angka.getText() + "1");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_satuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        angka.setText(angka.getText() + "2");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        angka.setText(angka.getText() + "3");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        angka.setText(angka.getText() + "4");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        angka.setText(angka.getText() + "5");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_limaActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        angka.setText(angka.getText() + "6");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        angka.setText(angka.getText() + "7");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        angka.setText(angka.getText() + "8");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        angka.setText(angka.getText() + "9");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_sembilanActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        angka.setText(angka.getText() + "0");
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
    }//GEN-LAST:event_nolActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        label_pesan.setText("Silahkan masukkan angka pengaturan dengan benar sesuai perintah yang diinginkan..!!!");
        if (angka.getText().length() > 0) {
            StringBuffer sb = new StringBuffer(angka.getText());
            sb = sb.deleteCharAt(angka.getText().length() - 1);
            angka.setText(sb.toString());
        }
    }//GEN-LAST:event_backspaceActionPerformed

    private void BtnCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseAppActionPerformed
        if (angka.getText().equals("")) {
            label_pesan.setText("Angka Pengaturan tidak boleh kosong, silahkan isi "
                    + "PIN dengan benar untuk menutup Aplikasi ini..!!!");
            angka.requestFocus();
        } else {
            if (Sequel.cariInteger("select count(-1) from antrian_hak_akses where pin_admin_utama='" + angka.getText() + "'") > 0) {
                int jawab = JOptionPane.showConfirmDialog(null, "Yakin anda mau keluar dari program ini...????", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (jawab == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            } else {
                label_pesan.setText("Angka PIN yang anda masukkan salah, silahkan ulangi "
                        + "lagi dengan benar untuk menutup Aplikasi ini (Hanya Admin Utama)..!!!");
                angka.requestFocus();
            }
        }
    }//GEN-LAST:event_BtnCloseAppActionPerformed

    private void BtnAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAktifActionPerformed
        cekNomor = "";
        cekNomor = "tidak";
        loket_umum.setEnabled(true);
        loket_bpjs.setEnabled(true);
        loket_inap.setEnabled(true);
        loket_khusus.setEnabled(true);
        label_pesan.setText("Semua tombol nomor antrian loket telah diaktifkan..!!");
    }//GEN-LAST:event_BtnAktifActionPerformed

    private void BtnNonAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNonAktifActionPerformed
        cekNomor = "";
        cekNomor = "tidak";
        loket_umum.setEnabled(false);
        loket_bpjs.setEnabled(false);
        loket_inap.setEnabled(false);
        loket_khusus.setEnabled(false);
        label_pesan.setText("Semua tombol nomor antrian loket telah dinonaktifkan dulu untuk sementara..!!");
    }//GEN-LAST:event_BtnNonAktifActionPerformed

    private void BtnResetAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetAngkaActionPerformed
        angka.setText("");
        angka.requestFocus();
    }//GEN-LAST:event_BtnResetAngkaActionPerformed

    private void satu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satu1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "1");
    }//GEN-LAST:event_satu1ActionPerformed

    private void dua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dua1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "2");
    }//GEN-LAST:event_dua1ActionPerformed

    private void tiga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiga1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "3");
    }//GEN-LAST:event_tiga1ActionPerformed

    private void empat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empat1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "4");
    }//GEN-LAST:event_empat1ActionPerformed

    private void lima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lima1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "5");
    }//GEN-LAST:event_lima1ActionPerformed

    private void enam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enam1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "6");
    }//GEN-LAST:event_enam1ActionPerformed

    private void tujuh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuh1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "7");
    }//GEN-LAST:event_tujuh1ActionPerformed

    private void delapan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapan1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "8");
    }//GEN-LAST:event_delapan1ActionPerformed

    private void sembilan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilan1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "9");
    }//GEN-LAST:event_sembilan1ActionPerformed

    private void nol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nol1ActionPerformed
        pinLogin.setText(pinLogin.getText() + "0");
    }//GEN-LAST:event_nol1ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (pinLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan masukkan PIN dengan benar,..!!!");
            pinLogin.requestFocus();
        } else if (Sequel.cariInteger("select count(-1) from antrian_hak_akses where pin_petugas='" + pinLogin.getText() + "'") > 0) {
            WindowPengaturan.setSize(992, 589);
            WindowPengaturan.setLocationRelativeTo(PanelUtama);
            WindowPengaturan.setVisible(true);
            label_pesan.setText("Apa yang anda pikirkan...!!!");
            angka.setText("");
            BtnNonAktif.requestFocus();
            BtnKertas.setEnabled(true);
            BtnSetUmum.setEnabled(false);
            BtnSetBPJS.setEnabled(false);
            BtnSetInap.setEnabled(false);
            BtnSetKhusus.setEnabled(false);

            BtnResUmum.setEnabled(false);
            BtnResBPJS.setEnabled(false);
            BtnResInap.setEnabled(false);
            BtnResKhusus.setEnabled(false);
            logoutActionPerformed(null);
        } else if (Sequel.cariInteger("select count(-1) from antrian_hak_akses where pin_admin_utama='" + pinLogin.getText() + "'") > 0) {
            WindowPengaturan.setSize(992, 589);
            WindowPengaturan.setLocationRelativeTo(PanelUtama);
            WindowPengaturan.setVisible(true);
            label_pesan.setText("Apa yang anda pikirkan...!!!");
            angka.setText("");
            BtnNonAktif.requestFocus();
            BtnKertas.setEnabled(true);
            BtnSetUmum.setEnabled(true);
            BtnSetBPJS.setEnabled(true);
            BtnSetInap.setEnabled(true);
            BtnSetKhusus.setEnabled(true);

            BtnResUmum.setEnabled(true);
            BtnResBPJS.setEnabled(true);
            BtnResInap.setEnabled(true);
            BtnResKhusus.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "PIN yang anda masukkan salah,..!!!");
            pinLogin.setText("");
            pinLogin.requestFocus();
            WindowPengaturan.dispose();
        }
    }//GEN-LAST:event_okActionPerformed

    private void backspace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspace1ActionPerformed
        if (pinLogin.getText().length() > 0) {
            StringBuffer sb = new StringBuffer(pinLogin.getText());
            sb = sb.deleteCharAt(pinLogin.getText().length() - 1);
            pinLogin.setText(sb.toString());
        }
    }//GEN-LAST:event_backspace1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        pinLogin.setText("");
        WindowLogin.dispose();
        cekTIDAK();
//        cekKertas();        
    }//GEN-LAST:event_logoutActionPerformed

    private void angkaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCloseAppActionPerformed(null);
        }
    }//GEN-LAST:event_angkaKeyPressed

    private void loket_umumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loket_umumActionPerformed
        cekNomor = "";
        cekNomor = "ya";
        loket_umum.setEnabled(false);
        loket_bpjs.setEnabled(false);
        loket_inap.setEnabled(false);
        loket_khusus.setEnabled(false);
        persenTombol();
//        kertasTerpotong();
        persenNomor();
        NoAntrianUmum();       
    }//GEN-LAST:event_loket_umumActionPerformed

    private void loket_bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loket_bpjsActionPerformed
        cekNomor = "";
        cekNomor = "ya";
        loket_umum.setEnabled(false);
        loket_bpjs.setEnabled(false);
        loket_inap.setEnabled(false);
        loket_khusus.setEnabled(false);
        persenTombol();
//        kertasTerpotong();
        persenNomor();
        NoAntrianBPJS();
    }//GEN-LAST:event_loket_bpjsActionPerformed

    private void pinLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            okActionPerformed(null);
        }
    }//GEN-LAST:event_pinLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgNomorAntrian dialog = new DlgNomorAntrian(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAktif;
    private widget.Button BtnCloseApp;
    private widget.Button BtnKeluar;
    private widget.Button BtnKertas;
    private widget.Button BtnNonAktif;
    private widget.Button BtnResBPJS;
    private widget.Button BtnResInap;
    private widget.Button BtnResKhusus;
    private widget.Button BtnResUmum;
    private widget.Button BtnResetAngka;
    private widget.Button BtnSetBPJS;
    private widget.Button BtnSetInap;
    private widget.Button BtnSetKhusus;
    private widget.Button BtnSetUmum;
    private javax.swing.JPanel PanelUtama;
    public usu.widget.glass.PanelGlass PanelWallNomor;
    private javax.swing.JDialog WindowLogin;
    private javax.swing.JDialog WindowPengaturan;
    private widget.TextBox angka;
    private widget.InternalFrame antrian_terakhir;
    private widget.Button backspace;
    private widget.Button backspace1;
    private javax.swing.ButtonGroup buttonGroup1;
    private widget.Button delapan;
    private widget.Button delapan1;
    private widget.Button dua;
    private widget.Button dua1;
    private widget.Button empat;
    private widget.Button empat1;
    private widget.Button enam;
    private widget.Button enam1;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame10;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.InternalFrame internalFrame4;
    private widget.InternalFrame internalFrame5;
    private widget.InternalFrame internalFrame6;
    private widget.InternalFrame internalFrame7;
    private widget.InternalFrame internalFrame8;
    private widget.InternalFrame internalFrame9;
    private widget.Label jLabel13;
    private widget.Label jLabel14;
    private widget.Label jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel kertas;
    private javax.swing.JLabel labe4;
    private javax.swing.JLabel labe6;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private widget.Label label_box;
    private javax.swing.JLabel label_judul1;
    private javax.swing.JLabel label_judul2;
    private widget.TextArea label_pesan;
    private widget.Button lima;
    private widget.Button lima1;
    private widget.Button logout;
    private widget.Button loket_bpjs;
    private widget.Button loket_inap;
    private widget.Button loket_khusus;
    private widget.Button loket_umum;
    private javax.swing.JLabel no_loket_bpjs;
    private javax.swing.JLabel no_loket_inap;
    private javax.swing.JLabel no_loket_khusus;
    private javax.swing.JLabel no_loket_umum;
    private widget.Button nol;
    private widget.Button nol1;
    private widget.Button ok;
    private widget.PasswordBox pinLogin;
    private widget.ProgressBar prosesNomor;
    private widget.ProgressBar prosesTombol;
    private widget.Button satu;
    private widget.Button satu1;
    private widget.ScrollPane scrollPane1;
    private widget.Button sembilan;
    private widget.Button sembilan1;
    private widget.Button seting;
    private widget.Button tiga;
    private widget.Button tiga1;
    private widget.InternalFrame tombol;
    private widget.Button tujuh;
    private widget.Button tujuh1;
    // End of variables declaration//GEN-END:variables

    private void TimerStart() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (d == 0) {
                    dispose();  
                    BtnKeluarActionPerformed(null);
                } else {
                    d = 0;
                    PanelWallNomor.requestFocus();
                    persenNomor();
//                    cekKertas();
                }
            }
        };
        // Timer
        new Timer(120000, taskPerformer).start();
//        new Timer(3000, taskPerformer).start();
    }
    
    public void cekTIDAK() {
        d = 1;
        loket_umum.setEnabled(true);
        loket_bpjs.setEnabled(true);
        loket_inap.setEnabled(true);
        loket_khusus.setEnabled(true);        
    }   
   
    private void NoAntrianUmum() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Sequel.menyimpan("antrian_nomor_umum", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_umum where date(waktu_cetak)=date(now())") + "',"
                + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan Umum (Non BPJS)");
        
        Map<String, Object> param = new HashMap<>();
        param.put("logo", Sequel.cariGambar("select logo_hitam_putih from setting"));
//        Valid.MyReport("rptNomorAntrianUmum.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan Umum (Non BPJS) ]::",
//                "SELECT concat('PU-',max(no_antrian)) nomor from antrian_nomor_umum where date(waktu_cetak)=date(now())", param);

        Valid.AutoMultiPrint("rptNomorAntrianUmum.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan Umum (Non BPJS) ]::",
                "SELECT concat('PU-',max(no_antrian)) nomor from antrian_nomor_umum where date(waktu_cetak)=date(now())", param, nmPrinter);
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    private void NoAntrianBPJS() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Sequel.menyimpan("antrian_nomor_bpjs", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_bpjs where date(waktu_cetak)=date(now())") + "',"
                + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan BPJS");

        Map<String, Object> param = new HashMap<>();
        param.put("logo", Sequel.cariGambar("select logo_hitam_putih from setting"));
//        Valid.MyReport("rptNomorAntrianBPJS.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan BPJS ]::",
//                "SELECT max(no_antrian) nomor from antrian_nomor_bpjs where date(waktu_cetak)=date(now())", param);

        Valid.AutoMultiPrint("rptNomorAntrianBPJS.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan BPJS ]::",
                "SELECT max(no_antrian) nomor from antrian_nomor_bpjs where date(waktu_cetak)=date(now())", param, nmPrinter);
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    private void NoAntrianINAP() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Sequel.menyimpan("antrian_nomor_inap", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_inap where date(waktu_cetak)=date(now())") + "',"
                + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Inap");

        Map<String, Object> param = new HashMap<>();
        param.put("logo", Sequel.cariGambar("select logo_hitam_putih from setting"));
//        Valid.MyReport("rptNomorAntrianInap.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Inap ]::",
//                "SELECT max(no_antrian) nomor from antrian_nomor_inap where date(waktu_cetak)=date(now())", param);

        Valid.AutoMultiPrint("rptNomorAntrianInap.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Inap ]::",
                "SELECT max(no_antrian) nomor from antrian_nomor_inap where date(waktu_cetak)=date(now())", param, nmPrinter);
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    private void NoAntrianKHUSUS() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));        
        Sequel.menyimpan("antrian_nomor_lansia", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor_lansia where date(waktu_cetak)=date(now())") + "',"
                + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan (Khusus/Prioritas)");

        Map<String, Object> param = new HashMap<>();
        param.put("logo", Sequel.cariGambar("select logo_hitam_putih from setting"));
//        Valid.MyReport("rptNomorAntrianLansia.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan (Khusus/Prioritas) ]::",
//                "SELECT max(no_antrian) nomor from antrian_nomor_lansia where date(waktu_cetak)=date(now())", param);

        Valid.AutoMultiPrint("rptNomorAntrianLansia.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan (Khusus/Prioritas) ]::",
                "SELECT max(no_antrian) nomor from antrian_nomor_lansia where date(waktu_cetak)=date(now())", param, nmPrinter);
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    private void persenNomor() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //proses bar diatur 2%. nilai i < 3 hasilnya 2%
                for (int i = 0; i < 3; i++) {
                    try {
                        prosesNomor.setValue(i);
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DlgNomorAntrian.class.getName()).log(Level.SEVERE, null, ex);                        
                    }
                }

                if (prosesNomor.getString().equals("2%")) {
//                    hitungSisaKertas();
                    cekNoTerakhirUmum();
                    cekNoTerakhirBPJS();
                    cekNoTerakhirKhusus();
                    cekNoTerakhirInap();
                }
            }
        });

        t.start();
    }
    
    private void persenTombol() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //proses bar diatur 50%. nilai i < 51 hasilnya 50%
                for (int i = 0; i < 51; i++) {
                    try {
                        prosesTombol.setValue(i);
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DlgNomorAntrian.class.getName()).log(Level.SEVERE, null, ex);                        
                    }
                }

                if (prosesTombol.getString().equals("50%")) {
//                    if (c > 0) {
                        cekTIDAK();
//                    }
                }
            }
        });

        t.start();
    }
    
//    private void hitungSisaKertas() {
//        a = 0;
//        b = 0;
//        c = 0;
//        
//        a = Integer.parseInt(Sequel.cariIsi("select counter_kertas_roll from antrian_set_kertas where kd_kertas='" + label_box.getText() + "'"));
//        b = Integer.parseInt(Sequel.cariIsi("select counter_kertas_antrian from antrian_set_kertas where kd_kertas='" + label_box.getText() + "'"));
//        
//        c = a - b;
//        kertas.setText("Kertas terpotong : " + Sequel.cariIsi("select counter_kertas_antrian from antrian_set_kertas "
//                + "where kd_kertas='" + label_box.getText() + "'") + " lembar, dan sisa kertas masih lagi : " + c + " lembar.");        
//    }
    
//    private void kertasTerpotong() {
//        a = 0;
//        b = 0;
//        
//        a = Integer.parseInt(Sequel.cariIsi("select counter_kertas_antrian from antrian_set_kertas where kd_kertas='" + label_box.getText() + "'"));
//        b = a + 1;
//        
//        Sequel.mengedit("antrian_set_kertas", "kd_kertas='" + label_box.getText() + "'", "counter_kertas_antrian=" + b + "");
//        cekKertas();
//    }
    
//    private void cekKertas() {
//        if (Sequel.cariInteger("select count(counter_kertas_antrian) from antrian_set_kertas "
//                + "where counter_kertas_roll=counter_kertas_antrian and kd_kertas='" + label_box.getText() + "'") == 1) {
//            internalFrame2.setWarnaAtas(Color.red);
//            internalFrame2.setWarnaBawah(Color.red);
//            internalFrame3.setWarnaAtas(Color.red);
//            internalFrame3.setWarnaBawah(Color.red);
//            label_judul1.setForeground(Color.white);
//            label_judul2.setForeground(Color.white);
//            label_judul1.setText("MOHON MAAF, SEMENTARA ANDA BELUM BISA MENGAMBIL NOMOR ANTRIAN,");
//            label_judul2.setText("KERTAS PADA PRINTER SUDAH HABIS. SILAHKAN HUBUNGI PETUGAS RUMAH SAKIT.");
//            cekNomor = "";
//            cekNomor = "ya";
//            loket_umum.setEnabled(false);
//            loket_bpjs.setEnabled(false);
//            loket_inap.setEnabled(false);
//            loket_lansia_bayi.setEnabled(false);
//        } else {            
//            internalFrame2.setWarnaAtas(getBackground());
//            internalFrame2.setWarnaBawah(getBackground());
//            internalFrame3.setWarnaAtas(getBackground());
//            internalFrame3.setWarnaBawah(getBackground());
//            label_judul1.setForeground(Color.black);
//            label_judul2.setForeground(Color.black);
//            label_judul1.setText("SILAHKAN TEKAN TOMBOL YANG ANDA PILIH");
//            label_judul2.setText("UNTUK MENGAMBIL NOMOR ANTRIAN");
//        }
//    }
    
    private void cekNoTerakhirUmum() {
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_umum where date(waktu_cetak)=date(now())") < 1) {
            no_loket_umum.setText("Terakhir : 0");
        } else {
            try {
                ps1 = koneksi.prepareStatement("select max(no_antrian) from antrian_nomor_umum where date(waktu_cetak)=date(now())");
                try {
                    rs1 = ps1.executeQuery();
                    if (rs1.next()) {
                        no_loket_umum.setText("Terakhir : " + rs1.getString(1));
                    }
                } catch (Exception e) {
                } finally {
                    if (rs1 != null) {
                        rs1.close();
                    }

                    if (ps1 != null) {
                        ps1.close();
                    }
                }
            } catch (Exception e) {
            }
        }
    }

    private void cekNoTerakhirBPJS() {
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_bpjs where date(waktu_cetak)=date(now())") < 1) {
            no_loket_bpjs.setText("Terakhir : 0");
        } else {
            try {
                ps2 = koneksi.prepareStatement("select max(no_antrian) from antrian_nomor_bpjs where date(waktu_cetak)=date(now())");
                try {
                    rs2 = ps2.executeQuery();
                    if (rs2.next()) {
                        no_loket_bpjs.setText("Terakhir : " + rs2.getString(1));
                    }
                } catch (Exception e) {
                } finally {
                    if (rs2 != null) {
                        rs2.close();
                    }

                    if (ps2 != null) {
                        ps2.close();
                    }
                }
            } catch (Exception e) {
            }
        }
    }

    private void cekNoTerakhirInap() {
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_inap where date(waktu_cetak)=date(now())") < 1) {
            no_loket_inap.setText("Terakhir : 0");
        } else {
            try {
                ps3 = koneksi.prepareStatement("select max(no_antrian) from antrian_nomor_inap where date(waktu_cetak)=date(now())");
                try {
                    rs3 = ps3.executeQuery();
                    if (rs3.next()) {
                        no_loket_inap.setText("Terakhir : " + rs3.getString(1));
                    }
                } catch (Exception e) {
                } finally {
                    if (rs3 != null) {
                        rs3.close();
                    }

                    if (ps3 != null) {
                        ps3.close();
                    }
                }
            } catch (Exception e) {
            }
        }
    }

    private void cekNoTerakhirKhusus() {
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_lansia where date(waktu_cetak)=date(now())") < 1) {
            no_loket_khusus.setText("Terakhir : 0");
        } else {
            try {
                ps4 = koneksi.prepareStatement("select max(no_antrian) from antrian_nomor_lansia where date(waktu_cetak)=date(now())");
                try {
                    rs4 = ps4.executeQuery();
                    if (rs4.next()) {
                        no_loket_khusus.setText("Terakhir : " + rs4.getString(1));
                    }
                } catch (Exception e) {
                } finally {
                    if (rs4 != null) {
                        rs4.close();
                    }

                    if (ps4 != null) {
                        ps4.close();
                    }
                }
            } catch (Exception e) {
            }
        }
    }
    
    public void cekHariLibur() {
        now = dateformat2.format(date);
        if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = '" + now + "'") > 0) {
            try {
                Runtime runtime = Runtime.getRuntime();
                Process proc = runtime.exec("shutdown -s -t 10");
                System.exit(0);
            } catch (Exception e) {
            }
        }
    }
}
