/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package simrskhanza;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import static mondrian.olap.fun.vba.Vba.date;

/**
 *
 * @author perpustakaan
 */
public class frmUtamaNirwana extends javax.swing.JFrame {
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private static frmUtamaNirwana myInstance;
    private final Properties prop = new Properties();
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
    private Date date = new Date();
    private String now = dateformat2.format(date), cekNomor = "", nmPrinter = "";
    private int n = 0;
    
    public frmUtamaNirwana(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();   
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/users.png")).getImage());
        
        jam();
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
        } catch (Exception e) {
            System.out.println("SEP XML : "+e);
        }
        
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
//            label_box.setText(koneksiDB.NOMORBOX());
            nmPrinter = koneksiDB.NAMAPRINTER1();
        } catch (Exception e) {
            System.out.println("SEP XML : "+e);
        }                
        persenNomor();
    }
    
    /**
     * Creates new form frmUtama
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnRefresNomor = new javax.swing.JMenuItem();
        MnTutup = new javax.swing.JMenuItem();
        prosesTombol = new widget.ProgressBar();
        prosesNomor = new widget.ProgressBar();
        internalFrame1 = new widget.InternalFrame();
        internalFrame7 = new widget.InternalFrame();
        internalFrame5 = new widget.InternalFrame();
        tgljam = new javax.swing.JLabel();
        internalFrame4 = new widget.InternalFrame();
        lblStts = new javax.swing.JLabel();
        PanelUtama = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        internalFrame3 = new widget.InternalFrame();
        internalFrame6 = new widget.InternalFrame();
        tombol = new widget.InternalFrame();
        no_loket = new javax.swing.JLabel();
        antrian_terakhir = new widget.InternalFrame();
        text1 = new javax.swing.JLabel();
        loket = new widget.Button();
        text2 = new javax.swing.JLabel();
        internalFrame2 = new widget.InternalFrame();
        judulAnjungan = new javax.swing.JLabel();
        internalFrame8 = new widget.InternalFrame();
        label3 = new javax.swing.JLabel();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        MnRefresNomor.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnRefresNomor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        MnRefresNomor.setText("Refresh Nomor");
        MnRefresNomor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnRefresNomor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnRefresNomor.setName("MnRefresNomor"); // NOI18N
        MnRefresNomor.setPreferredSize(new java.awt.Dimension(130, 26));
        MnRefresNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRefresNomorActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnRefresNomor);

        MnTutup.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        MnTutup.setText("Tutup Aplikasi");
        MnTutup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnTutup.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnTutup.setName("MnTutup"); // NOI18N
        MnTutup.setPreferredSize(new java.awt.Dimension(130, 26));
        MnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTutupActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnTutup);

        prosesTombol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prosesTombol.setName("prosesTombol"); // NOI18N
        prosesTombol.setPreferredSize(new java.awt.Dimension(160, 40));
        prosesTombol.setStringPainted(true);

        prosesNomor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prosesNomor.setName("prosesNomor"); // NOI18N
        prosesNomor.setPreferredSize(new java.awt.Dimension(160, 40));
        prosesNomor.setStringPainted(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ Anjungan Elektronik Pasien ]::");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(40, 105));
        internalFrame1.setVerifyInputWhenFocusTarget(false);
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setPreferredSize(new java.awt.Dimension(330, 50));
        internalFrame7.setWarnaAtas(new java.awt.Color(177, 210, 61));
        internalFrame7.setWarnaBawah(new java.awt.Color(177, 210, 61));
        internalFrame7.setLayout(new java.awt.BorderLayout());
        internalFrame1.add(internalFrame7, java.awt.BorderLayout.PAGE_START);

        internalFrame5.setBorder(null);
        internalFrame5.setName("internalFrame5"); // NOI18N
        internalFrame5.setPreferredSize(new java.awt.Dimension(330, 56));
        internalFrame5.setWarnaAtas(new java.awt.Color(177, 210, 61));
        internalFrame5.setLayout(new java.awt.BorderLayout());

        tgljam.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        tgljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgljam.setText("Tanggal & Jam Sekarang");
        tgljam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgljam.setName("tgljam"); // NOI18N
        tgljam.setPreferredSize(new java.awt.Dimension(100, 25));
        internalFrame5.add(tgljam, java.awt.BorderLayout.CENTER);

        internalFrame1.add(internalFrame5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.PAGE_START);

        internalFrame4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 235, 205)));
        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(330, 25));
        internalFrame4.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame4.setWarnaBawah(new java.awt.Color(177, 210, 61));
        internalFrame4.setLayout(new java.awt.BorderLayout());

        lblStts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStts.setText("Powered by. SIMRS RSU Nirwana Copyright@2026");
        lblStts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblStts.setName("lblStts"); // NOI18N
        lblStts.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame4.add(lblStts, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame4, java.awt.BorderLayout.PAGE_END);

        PanelUtama.setName("PanelUtama"); // NOI18N
        PanelUtama.setLayout(new java.awt.BorderLayout());

        PanelWall.setBackground(new java.awt.Color(29, 29, 29));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpaper_nirwana.jpg"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setPreferredSize(new java.awt.Dimension(200, 205));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(110, 110, 110));
        PanelWall.setLayout(new java.awt.BorderLayout());

        internalFrame3.setBorder(null);
        internalFrame3.setName("internalFrame3"); // NOI18N
        internalFrame3.setOpaque(false);
        internalFrame3.setPreferredSize(new java.awt.Dimension(330, 80));
        internalFrame3.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame3.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame3.setLayout(new java.awt.BorderLayout());

        internalFrame6.setBorder(null);
        internalFrame6.setName("internalFrame6"); // NOI18N
        internalFrame6.setOpaque(false);
        internalFrame6.setPreferredSize(new java.awt.Dimension(0, 270));
        internalFrame6.setLayout(new java.awt.BorderLayout());

        tombol.setBorder(null);
        tombol.setComponentPopupMenu(jPopupMenu1);
        tombol.setName("tombol"); // NOI18N
        tombol.setOpaque(false);
        tombol.setPreferredSize(new java.awt.Dimension(330, 290));
        tombol.setWarnaAtas(new java.awt.Color(255, 255, 255));
        tombol.setWarnaBawah(new java.awt.Color(255, 204, 0));
        tombol.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 15));

        no_loket.setFont(new java.awt.Font("Tahoma", 1, 270)); // NOI18N
        no_loket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_loket.setText("0");
        no_loket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_loket.setName("no_loket"); // NOI18N
        no_loket.setPreferredSize(new java.awt.Dimension(800, 240));
        tombol.add(no_loket);

        internalFrame6.add(tombol, java.awt.BorderLayout.PAGE_END);

        internalFrame3.add(internalFrame6, java.awt.BorderLayout.PAGE_START);

        antrian_terakhir.setBorder(null);
        antrian_terakhir.setComponentPopupMenu(jPopupMenu1);
        antrian_terakhir.setName("antrian_terakhir"); // NOI18N
        antrian_terakhir.setOpaque(false);
        antrian_terakhir.setPreferredSize(new java.awt.Dimension(330, 300));
        antrian_terakhir.setWarnaAtas(new java.awt.Color(255, 255, 255));
        antrian_terakhir.setWarnaBawah(new java.awt.Color(255, 204, 0));
        antrian_terakhir.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        text1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("{");
        text1.setComponentPopupMenu(jPopupMenu1);
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text1.setName("text1"); // NOI18N
        text1.setPreferredSize(new java.awt.Dimension(70, 300));
        antrian_terakhir.add(text1);

        loket.setBorder(null);
        loket.setForeground(new java.awt.Color(0, 0, 0));
        loket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/telunjuk_jari.png"))); // NOI18N
        loket.setToolTipText("");
        loket.setBorderPainted(true);
        loket.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loket.setGlassColor(new java.awt.Color(255, 0, 51));
        loket.setName("loket"); // NOI18N
        loket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loketActionPerformed(evt);
            }
        });
        antrian_terakhir.add(loket);

        text2.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2.setText("}");
        text2.setToolTipText("");
        text2.setComponentPopupMenu(jPopupMenu1);
        text2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text2.setName("text2"); // NOI18N
        text2.setPreferredSize(new java.awt.Dimension(70, 300));
        antrian_terakhir.add(text2);

        internalFrame3.add(antrian_terakhir, java.awt.BorderLayout.PAGE_END);

        internalFrame2.setBorder(null);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setOpaque(false);
        internalFrame2.setPreferredSize(new java.awt.Dimension(330, 30));
        internalFrame2.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame2.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame2.setLayout(new java.awt.BorderLayout());

        judulAnjungan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judulAnjungan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulAnjungan.setText("[ TEKAN TOMBOL DIBAWAH INI UNTUK AMBIL NOMOR ANTRIAN ]");
        judulAnjungan.setComponentPopupMenu(jPopupMenu1);
        judulAnjungan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        judulAnjungan.setName("judulAnjungan"); // NOI18N
        judulAnjungan.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame2.add(judulAnjungan, java.awt.BorderLayout.CENTER);

        internalFrame3.add(internalFrame2, java.awt.BorderLayout.CENTER);

        PanelWall.add(internalFrame3, java.awt.BorderLayout.CENTER);

        internalFrame8.setName("internalFrame8"); // NOI18N
        internalFrame8.setOpaque(false);
        internalFrame8.setPreferredSize(new java.awt.Dimension(330, 38));
        internalFrame8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 0));

        label3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Nomor Antrian Terakhir");
        label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label3.setName("label3"); // NOI18N
        label3.setPreferredSize(new java.awt.Dimension(300, 35));
        internalFrame8.add(label3);

        PanelWall.add(internalFrame8, java.awt.BorderLayout.PAGE_START);

        PanelUtama.add(PanelWall, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cekHariLibur();
    }//GEN-LAST:event_formWindowOpened

    private void loketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loketActionPerformed
        cekNomor = "";
        cekNomor = "ya";
        loket.setEnabled(false);
        persenTombol();
        //        kertasTerpotong();
        persenNomor();
        NoAntrian();
    }//GEN-LAST:event_loketActionPerformed

    private void MnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTutupActionPerformed
        int jawab = JOptionPane.showConfirmDialog(null, "Yakin anda mau keluar dari Aplikasi ini...????", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MnTutupActionPerformed

    private void MnRefresNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRefresNomorActionPerformed
        cekNoTerakhir();
    }//GEN-LAST:event_MnRefresNomorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnRefresNomor;
    private javax.swing.JMenuItem MnTutup;
    private javax.swing.JPanel PanelUtama;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.InternalFrame antrian_terakhir;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.InternalFrame internalFrame4;
    private widget.InternalFrame internalFrame5;
    private widget.InternalFrame internalFrame6;
    private widget.InternalFrame internalFrame7;
    private widget.InternalFrame internalFrame8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel judulAnjungan;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lblStts;
    private widget.Button loket;
    private javax.swing.JLabel no_loket;
    private widget.ProgressBar prosesNomor;
    private widget.ProgressBar prosesTombol;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel tgljam;
    private widget.InternalFrame tombol;
    // End of variables declaration//GEN-END:variables

//    public void updateBooking() {
//        now = dateformat2.format(date);
//        Sequel.mengedit("booking_registrasi", "tanggal_periksa < '" + now + "' and status_booking = 'Menunggu'", "status_booking='Batal'");
//    }

    public void cekHariLibur() {        
        //antrian direset mundur 2 hari
        resetPanggilanAntrian();
        resetNomorAntrian();
        Sequel.queryu("delete from antrian_history_reset where date(tgl_reset) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");        
        
//        now = dateformat2.format(date);
//        if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = '" + now + "'") > 0) {
//            try {
//                Runtime runtime = Runtime.getRuntime();
//                Process proc = runtime.exec("shutdown -s -t 10");
//                System.exit(0);
//            } catch (Exception e) {
//            }
//        }
    }
    
    private void resetPanggilanAntrian() {
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil where date(waktu_panggil)=date(now())") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT date(now())") + "'", "Nomor Antrian Panggilan");
            Sequel.queryu("delete from antrian_pemanggil where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void resetNomorAntrian() {
        if (Sequel.cariInteger("select count(-1) from antrian_nomor where date(waktu_cetak)=date(now())") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor where date(waktu_cetak)=date(now()) order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT date(now())") + "'", "Nomor Antrian Pasien");
            Sequel.queryu("delete from antrian_nomor where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void isTutup() {
        akses.setform("frmUtamaNirwana");
        Window[] wins = Window.getWindows();
        for (Window win : wins) {
            if (win instanceof JDialog) {
                win.dispose();
            }
        }
    }
    
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;

            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";

                Date now = Calendar.getInstance().getTime();

                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                    nilai_jam = now.getHours();
                    nilai_menit = now.getMinutes();
                    nilai_detik = now.getSeconds();

                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                
                // Menampilkan pada Layar                
                tgljam.setText("Hari ini Tgl. " + Valid.SetTglINDONESIA(Sequel.cariIsi("SELECT DATE(NOW())")) + ", Pukul. " + jam + ":" + menit + ":" + detik + " WITA");
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
    
    private void persenTombol() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //proses bar diatur 50%. nilai i < 51 hasilnya 50%
                for (int i = 0; i < 51; i++) {
                    try {
                        prosesTombol.setValue(i);
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DlgNomorAntrian.class.getName()).log(Level.SEVERE, null, ex);                        
                    }
                }

                if (prosesTombol.getString().equals("50%")) {
                    cekTIDAK();
                }
            }
        });

        t.start();
    }
    
    public void cekTIDAK() {
        n = 1;
        loket.setEnabled(true);
    }
    
    private void persenNomor() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //proses bar diatur 2%. nilai i < 3 hasilnya 2%
                for (int i = 0; i < 3; i++) {
                    try {
                        prosesNomor.setValue(i);
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DlgNomorAntrian.class.getName()).log(Level.SEVERE, null, ex);                        
                    }
                }

                if (prosesNomor.getString().equals("2%")) {
                    cekNoTerakhir();
                }
            }
        });

        t.start();
    }
    
    private void cekNoTerakhir() {
        if (Sequel.cariInteger("select count(-1) from antrian_nomor where date(waktu_cetak)=date(now())") < 1) {
            no_loket.setText("0");
        } else {
            try {
                ps = koneksi.prepareStatement("select max(no_antrian) from antrian_nomor where date(waktu_cetak)=date(now())");
                try {
                    rs = ps.executeQuery();
                    if (rs.next()) {
                        no_loket.setText(rs.getString(1));
                    }
                } catch (Exception e) {
                } finally {
                    if (rs != null) {
                        rs.close();
                    }

                    if (ps != null) {
                        ps.close();
                    }
                }
            } catch (Exception e) {
            }
        }
    }
    
    private void NoAntrian() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Sequel.menyimpan("antrian_nomor", "'" + Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_nomor where date(waktu_cetak)=date(now())") + "',"
                + "'oke','" + Sequel.cariIsi("select now()") + "'", "Nomor Antrian Pasien Rawat Jalan");
        
        Map<String, Object> param = new HashMap<>();
        if (Sequel.cariIsi("select auto_print_nomor_antrian_ralan from set_nota limit 1").equals("Yes")) {
            Valid.AutoMultiPrint("rptNomorAntrianNirwana.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan ]::",
                    "SELECT max(no_antrian) nomor from antrian_nomor where date(waktu_cetak)=date(now())", param, nmPrinter);
        } else {
            Valid.MyReport("rptNomorAntrianNirwana.jasper", "report", "::[ Cetak Nomor Antrian Pasien Rawat Jalan ]::",
                    "SELECT max(no_antrian) nomor from antrian_nomor where date(waktu_cetak)=date(now())", param);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }
}
