/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package simrskhanza;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import static mondrian.olap.fun.vba.Vba.date;

/**
 *
 * @author perpustakaan
 */
public class frmUtama extends javax.swing.JFrame {
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private static frmUtama myInstance;
    private final Properties prop = new Properties();
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
    private Date date = new Date();
    private String now = dateformat2.format(date);
    
    public frmUtama(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();   
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/users.png")).getImage());
        
        jam();
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
        } catch (Exception e) {
            System.out.println("SEP XML : "+e);
        }
    }
    
    /**
     * Creates new form frmUtama
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        internalFrame7 = new widget.InternalFrame();
        internalFrame3 = new widget.InternalFrame();
        no_antrian = new widget.Button();
        sep_bpjs = new widget.Button();
        internalFrame5 = new widget.InternalFrame();
        tgljam = new javax.swing.JLabel();
        internalFrame4 = new widget.InternalFrame();
        lblStts = new javax.swing.JLabel();
        PanelUtama = new javax.swing.JPanel();
        scrollPane1 = new widget.ScrollPane();
        PanelWall = new usu.widget.glass.PanelGlass();
        internalFrame2 = new widget.InternalFrame();
        internalFrame8 = new widget.InternalFrame();
        judulAnjungan = new javax.swing.JLabel();
        internalFrame9 = new widget.InternalFrame();
        jlabel1 = new javax.swing.JLabel();
        internalFrame6 = new widget.InternalFrame();
        label_pesan = new widget.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ Anjungan Elektronik Pasien ]::");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(null);
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setOpaque(false);
        internalFrame1.setPreferredSize(new java.awt.Dimension(40, 175));
        internalFrame1.setVerifyInputWhenFocusTarget(false);
        internalFrame1.setWarnaAtas(new java.awt.Color(153, 153, 153));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setPreferredSize(new java.awt.Dimension(330, 20));
        internalFrame7.setWarnaAtas(new java.awt.Color(83, 204, 251));
        internalFrame7.setWarnaBawah(new java.awt.Color(153, 153, 153));
        internalFrame7.setLayout(new java.awt.BorderLayout());
        internalFrame1.add(internalFrame7, java.awt.BorderLayout.PAGE_START);

        internalFrame3.setBorder(null);
        internalFrame3.setName("internalFrame3"); // NOI18N
        internalFrame3.setPreferredSize(new java.awt.Dimension(40, 80));
        internalFrame3.setVerifyInputWhenFocusTarget(false);
        internalFrame3.setWarnaAtas(new java.awt.Color(153, 153, 153));
        internalFrame3.setWarnaBawah(new java.awt.Color(255, 255, 255));
        internalFrame3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 9));

        no_antrian.setForeground(new java.awt.Color(0, 0, 0));
        no_antrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/1360485030_receipt.png"))); // NOI18N
        no_antrian.setText("NOMOR ANTRIAN LOKET");
        no_antrian.setToolTipText("");
        no_antrian.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        no_antrian.setGlassColor(new java.awt.Color(0, 0, 255));
        no_antrian.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        no_antrian.setName("no_antrian"); // NOI18N
        no_antrian.setPreferredSize(new java.awt.Dimension(460, 80));
        no_antrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_antrianActionPerformed(evt);
            }
        });
        internalFrame3.add(no_antrian);

        sep_bpjs.setForeground(new java.awt.Color(0, 0, 0));
        sep_bpjs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        sep_bpjs.setText("SEP BPJS KESEHATAN");
        sep_bpjs.setToolTipText("");
        sep_bpjs.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        sep_bpjs.setGlassColor(new java.awt.Color(0, 102, 102));
        sep_bpjs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sep_bpjs.setIconTextGap(15);
        sep_bpjs.setName("sep_bpjs"); // NOI18N
        sep_bpjs.setPreferredSize(new java.awt.Dimension(460, 80));
        sep_bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sep_bpjsActionPerformed(evt);
            }
        });
        internalFrame3.add(sep_bpjs);

        internalFrame1.add(internalFrame3, java.awt.BorderLayout.CENTER);

        internalFrame5.setBorder(null);
        internalFrame5.setName("internalFrame5"); // NOI18N
        internalFrame5.setPreferredSize(new java.awt.Dimension(330, 56));
        internalFrame5.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame5.setWarnaBawah(new java.awt.Color(83, 204, 251));
        internalFrame5.setLayout(new java.awt.BorderLayout());

        tgljam.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        tgljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgljam.setText("Tanggal & Jam Sekarang");
        tgljam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgljam.setName("tgljam"); // NOI18N
        tgljam.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame5.add(tgljam, java.awt.BorderLayout.CENTER);

        internalFrame1.add(internalFrame5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.PAGE_START);

        internalFrame4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 235, 205)));
        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setPreferredSize(new java.awt.Dimension(330, 25));
        internalFrame4.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame4.setWarnaBawah(new java.awt.Color(83, 204, 251));
        internalFrame4.setLayout(new java.awt.BorderLayout());

        lblStts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStts.setText("Powered by. UNIT SIMRS RSUD Ratu Zalecha Copyright@2019 versi 19.07.19 [Update 16.08.24]");
        lblStts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblStts.setName("lblStts"); // NOI18N
        lblStts.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame4.add(lblStts, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame4, java.awt.BorderLayout.PAGE_END);

        PanelUtama.setName("PanelUtama"); // NOI18N
        PanelUtama.setOpaque(false);
        PanelUtama.setLayout(new java.awt.BorderLayout());

        scrollPane1.setBorder(null);
        scrollPane1.setName("scrollPane1"); // NOI18N

        PanelWall.setBackground(new java.awt.Color(29, 29, 29));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpaper_hal_utama.jpg"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        PanelWall.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(110, 110, 110));
        PanelWall.setLayout(new java.awt.BorderLayout());

        internalFrame2.setBorder(null);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setOpaque(false);
        internalFrame2.setPreferredSize(new java.awt.Dimension(330, 328));
        internalFrame2.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame2.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame2.setLayout(new java.awt.BorderLayout());

        internalFrame8.setBorder(null);
        internalFrame8.setName("internalFrame8"); // NOI18N
        internalFrame8.setOpaque(false);
        internalFrame8.setPreferredSize(new java.awt.Dimension(330, 80));
        internalFrame8.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame8.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame8.setLayout(new java.awt.BorderLayout());

        judulAnjungan.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        judulAnjungan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulAnjungan.setText(".:: ANJUNGAN PASIEN ELEKTRONIK ::.");
        judulAnjungan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        judulAnjungan.setName("judulAnjungan"); // NOI18N
        judulAnjungan.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame8.add(judulAnjungan, java.awt.BorderLayout.CENTER);

        internalFrame2.add(internalFrame8, java.awt.BorderLayout.PAGE_START);

        internalFrame9.setBorder(null);
        internalFrame9.setName("internalFrame9"); // NOI18N
        internalFrame9.setOpaque(false);
        internalFrame9.setPreferredSize(new java.awt.Dimension(330, 100));
        internalFrame9.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame9.setWarnaBawah(new java.awt.Color(255, 204, 0));
        internalFrame9.setLayout(new java.awt.BorderLayout());

        jlabel1.setFont(new java.awt.Font("Tahoma", 1, 46)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(230, 33, 42));
        jlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel1.setText("SILAHKAN PILIH SALAH SATU MENU DIATAS");
        jlabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlabel1.setName("jlabel1"); // NOI18N
        jlabel1.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame9.add(jlabel1, java.awt.BorderLayout.CENTER);

        internalFrame2.add(internalFrame9, java.awt.BorderLayout.CENTER);

        internalFrame6.setBorder(null);
        internalFrame6.setName("internalFrame6"); // NOI18N
        internalFrame6.setOpaque(false);
        internalFrame6.setPreferredSize(new java.awt.Dimension(330, 200));
        internalFrame6.setWarnaAtas(new java.awt.Color(255, 255, 255));
        internalFrame6.setWarnaBawah(new java.awt.Color(255, 204, 0));

        label_pesan.setEditable(false);
        label_pesan.setColumns(20);
        label_pesan.setForeground(new java.awt.Color(0, 0, 0));
        label_pesan.setRows(5);
        label_pesan.setText("Untuk layanan pendaftaran online rawat jalan silakan     kirim pesan ke nomor 082351351297 via aplikasi           WhatsApp atau Telegram. Atau bisa juga lewat              website http://rsraza.banjarkab.go.id/epasien");
        label_pesan.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_pesan.setHighlighter(null);
        label_pesan.setName("label_pesan"); // NOI18N
        label_pesan.setPreferredSize(new java.awt.Dimension(1000, 40));
        internalFrame6.add(label_pesan);

        internalFrame2.add(internalFrame6, java.awt.BorderLayout.PAGE_END);

        PanelWall.add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        scrollPane1.setViewportView(PanelWall);

        PanelUtama.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sep_bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sep_bpjsActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        isTutup();
        DlgSEPbpjs utama =new DlgSEPbpjs(null, true);
        utama.empttext();
        utama.updateBooking();
        utama.cekHariLibur();
        utama.setSize(PanelUtama.getWidth(), PanelUtama.getHeight());
        utama.setLocationRelativeTo(PanelUtama);
        utama.kodeboking.requestFocus();
        utama.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_sep_bpjsActionPerformed

    private void no_antrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_antrianActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        isTutup();
        DlgNomorAntrian nomor = new DlgNomorAntrian(null, true);
        nomor.cekHariLibur();
        nomor.cekTIDAK();
        nomor.setSize(PanelUtama.getWidth(), PanelUtama.getHeight());
        nomor.setLocationRelativeTo(PanelUtama);
        nomor.PanelWallNomor.requestFocus();
        nomor.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_no_antrianActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cekHariLibur();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUtama;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.InternalFrame internalFrame4;
    private widget.InternalFrame internalFrame5;
    private widget.InternalFrame internalFrame6;
    private widget.InternalFrame internalFrame7;
    private widget.InternalFrame internalFrame8;
    private widget.InternalFrame internalFrame9;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel judulAnjungan;
    private widget.TextArea label_pesan;
    private javax.swing.JLabel lblStts;
    private widget.Button no_antrian;
    private widget.ScrollPane scrollPane1;
    private widget.Button sep_bpjs;
    private javax.swing.JLabel tgljam;
    // End of variables declaration//GEN-END:variables

    public void updateBooking() {
        now = dateformat2.format(date);
        Sequel.mengedit("booking_registrasi", "tanggal_periksa < '" + now + "' and status_booking = 'Menunggu'", "status_booking='Batal'");
    }

    public void cekHariLibur() {
        //antrian direset mundur 2 hari
        Sequel.queryu("delete from antrian_history_reset where date(tgl_reset) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        Sequel.queryu("delete from antrian_prioritas where date(waktu_simpan) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        
        now = dateformat2.format(date);
        if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = '" + now + "'") > 0) {
            try {
                Runtime runtime = Runtime.getRuntime();
                Process proc = runtime.exec("shutdown -s -t 10");
                System.exit(0);
            } catch (Exception e) {
            }
        }
    }
    
    private void isTutup() {
        akses.setform("frmUtama");
        Window[] wins = Window.getWindows();
        for (Window win : wins) {
            if (win instanceof JDialog) {
                win.dispose();
            }
        }
    }
    
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;

            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";

                Date now = Calendar.getInstance().getTime();

                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                    nilai_jam = now.getHours();
                    nilai_menit = now.getMinutes();
                    nilai_detik = now.getSeconds();

                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                
                // Menampilkan pada Layar                
                tgljam.setText("Hari ini Tgl. " + Valid.SetTglINDONESIA(Sequel.cariIsi("SELECT DATE(NOW())")) + ", Pukul. " + jam + ":" + menit + ":" + detik);
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
}
